---
title: "OutbreakOccurrenceAndSporeConcentration"
author: "Elizabeth Davenport"
date: '2023-04-03'
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initial stuff, including loading packages and importing data

##loading packages
```{r,message=F,warning=F}
library(tidyverse)
library(here)
library(ggpubr)
library(ggplot2)
library(dplyr)
library(lubridate)
library(scales)
library(reshape2)
library(gridExtra)
library(grid)
```

## loading files

```{r,message=F,warning=F}
# Tell R where files are stored
here::i_am("scripts/OutbreakOccurrenceAndSporeConcentration.Rmd")

# Load Files
a <- readr::read_csv(here("data/Metsch_Mean_Spores_Outbreak.csv"))
b <- readr::read_csv(here("data/Pasteuria_Mean_Spores_and_Percent_Infected_Outbreak.csv"))
c <- readr::read_csv(here("data/Brood_Mean_Spores_and_Percent_Infected_OutbreakSize.csv"))
d <- readr::read_csv(here("data/MicG_Mean_Spores_and_Percent_Infected_OutbreakSize.csv"))
```

```{r,message=F,warning=F}
# Setting color scheme and linetype for plots

cols3<- c("Walsh"= "yellow3",
          "Mill"= "#CC79A7","Bishop"="#0072B2","Cedar"= "#D55E00","CrookedW"= "#E69F00",
          "LilAp"="#009E73")

LT <- c("Yes"= "solid",
        "No"= "dashed")
```

```{r,message=F,warning=F}
# Metschnikowia bicuspidata
MestchDate <- a$datetime
strptime(MestchDate, format = "%m/%d/%y")
Mestchl <- as.POSIXct(MestchDate,format="%m/%d/%y",tz=Sys.timezone())
Mestchav <- a$Mean
Mestchlake <- a$Lake
Mestchlogavg<- log10(1+Mestchav)
Mestchoutbreak <- a$Outbreak

smooth.metsch <- ggplot(a) +
  geom_point(aes(x=Mestchl,y=Mestchlogavg, group=Mestchlake, color=Mestchlake), size=3) +
  geom_smooth(aes(x=Mestchl,y=Mestchlogavg, group = Mestchlake, color=Mestchlake, linetype=Mestchoutbreak),
              method = "loess", size = 1.5, span=.5, se=FALSE)+
  scale_y_continuous(limits = c(0, 6), breaks = seq(0, 6, 1)) +
  scale_x_datetime(limits = c(as.POSIXct(as.Date("2021-06-07")), as.POSIXct(as.Date("2021-11-13"))))+
  geom_point(aes(x = as.POSIXct(as.Date("2021-09-20"))), y=log10(3347.55+1), color="yellow3", shape=17,size=6)+
  scale_colour_manual(values = cols3)+  
  scale_linetype_manual(values=LT)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("M. bicuspidata") +
  theme(plot.title = element_text(face = "bold.italic",size = 22)) +
  theme(axis.text=element_text(size=20, face = "bold"), 
        axis.title=element_text(size=22,face="bold")) +
  theme(legend.title = element_text(face = "bold",size = 20),
        legend.text=element_text(size=18,face="bold"),
        legend.position = "bottom") +  
  labs(x = (""), y="Log(Mean Spore Concentration+1)", color="Lake", linetype="Outbreak?")+
  guides(linetype=guide_legend(nrow=2,byrow=TRUE))+  
  guides(color=guide_legend(nrow=2,byrow=TRUE))+
  theme(legend.key.width = unit(2, "cm"))

smooth.metsch
```

```{r,message=F,warning=F}
# Pasteuria ramosa
PastDate <- b$datetime
strptime(PastDate, format = "%m/%d/%y")
Pastl <- as.POSIXct(PastDate,format="%m/%d/%y",tz=Sys.timezone())
Pastav <- b$Mean
Pastlake <- b$Lake
Pastlogavg<- log10(1+Pastav)
Pastoutbreak <- b$Outbreak

smooth.past <- ggplot(b) +
  geom_point(aes(x=Pastl,y=Pastlogavg, group=Pastlake, color=Pastlake), size=3) +
  geom_smooth(aes(x=Pastl,y=Pastlogavg, group = Pastlake, color=Pastlake, linetype=Pastoutbreak),
              method = "loess", size = 1.5, span=.5, se=FALSE)+
  scale_y_continuous(limits = c(0, 6), breaks = seq(0, 6, 1)) +
  scale_x_datetime(limits = c(as.POSIXct(as.Date("2021-06-07")), as.POSIXct(as.Date("2021-11-13"))))+
  geom_point(aes(x = as.POSIXct(as.Date("2021-09-15"))), y=log10(396.2142857+1), color="#009E73", shape=17,size=6)+
  geom_point(aes(x = as.POSIXct(as.Date("2021-10-25"))), y=log10(73.71428571+1), color="#E69F00", shape=17,size=6)+
  geom_point(aes(x = as.POSIXct(as.Date("2021-08-23"))), y=log10(1543.241333+1), color="#CC79A7", shape=17,size=6)+
  geom_point(aes(x = as.POSIXct(as.Date("2021-08-18"))), y=log10(242.1821429+1), color="#0072B2", shape=17,size=6)+
  scale_colour_manual(values = cols3)+  
  scale_linetype_manual(values=LT)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("P. ramosa") +
  theme(plot.title = element_text(face = "bold.italic",size = 22)) +
  theme(axis.text=element_text(size=20, face = "bold"), 
        axis.title=element_text(size=22,face="bold")) +
  theme(legend.title = element_text(face = "bold",size = 20),
        legend.text=element_text(size=18,face="bold"),
        legend.position = "bottom") +  
  labs(x = (""), y="Log(Mean Spore Concentration+1)", color="Lake", linetype="Outbreak?")+
  guides(linetype=guide_legend(nrow=2,byrow=TRUE))+  
  guides(color=guide_legend(nrow=2,byrow=TRUE))+
  theme(legend.key.width = unit(2, "cm"))

smooth.past
```

```{r,message=F,warning=F}
# Blastulidium paedophthorum
Date <- c$datetime
strptime(Date, format = "%m/%d/%y")
l <- as.POSIXct(Date,format="%m/%d/%y",tz=Sys.timezone())
av <- c$Mean
m <- c$Max
lake <- c$Lake
logavg<- log10(1+av)
logmax <- log10(1+m)
outbreak <- c$Outbreak

smooth.brood <- ggplot(c) +
  geom_point(aes(x=l,y=logavg, group=lake, color=lake), size=3) +
  geom_smooth(aes(x=l,y=logavg, group = lake, color=lake, linetype=outbreak),
              method = "loess", size = 1.5, span=.5, se=FALSE)+
  scale_y_continuous(limits = c(0, 6), breaks = seq(0, 6, 1)) +
  scale_x_datetime(limits = c(as.POSIXct(as.Date("2021-06-07")), as.POSIXct(as.Date("2021-11-13"))))+
  geom_point(aes(x = as.POSIXct(as.Date("2021-07-06"))), y=log10(2894.207143+1), color="#D55E00", shape=17,size=6)+
  geom_point(aes(x = as.POSIXct(as.Date("2021-09-15"))), y=log10(27776.57847+1), color="#0072B2", shape=17,size=6)+
  geom_point(aes(x = as.POSIXct(as.Date("2021-08-23"))), y=log10(12963.92308+1), color="yellow3", shape=17,size=6)+
  scale_colour_manual(values = cols3)+
  scale_linetype_manual(values=LT)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("B. paedophthorum") +
  theme(plot.title = element_text(face = "bold.italic",size = 22)) +
  theme(axis.text=element_text(size=20, face = "bold"), 
        axis.title=element_text(size=24,face="bold")) +
  theme(legend.title = element_text(face = "bold",size = 20),
        legend.text=element_text(size=18,face="bold"),
        legend.position = "bottom") +  
  labs(x = (""), y="Log(Mean Spore Concentration+1)", color="Lake", linetype="Outbreak?")+
  guides(linetype=guide_legend(nrow=2,byrow=TRUE))+  
  guides(color=guide_legend(nrow=2,byrow=TRUE))+
  theme(legend.key.width = unit(2, "cm"))

smooth.brood
```

```{r,message=F,warning=F}
# Ordospora pajunii
MicGDate <- d$datetime
strptime(MicGDate, format = "%m/%d/%y")
MicGl <- as.POSIXct(MicGDate,format="%m/%d/%y",tz=Sys.timezone())
MicGav <- d$Mean
MicGlake <- d$Lake
MicGlogavg<- log10(1+MicGav)
MicGoutbreak <- d$Outbreak

smooth.MicG <- ggplot(d) +
  geom_point(aes(x=MicGl,y=MicGlogavg, group=MicGlake, color=MicGlake), size=3) +
  geom_smooth(aes(x=MicGl,y=MicGlogavg, group = MicGlake, color=MicGlake, linetype=MicGoutbreak),
              method = "loess", size = 1.5, span=.5, se=FALSE)+
  scale_y_continuous(limits = c(0, 6), breaks = seq(0, 6, 1)) +
  scale_x_datetime(limits = c(as.POSIXct(as.Date("2021-06-07")), as.POSIXct(as.Date("2021-11-13"))))+
  geom_point(aes(x = as.POSIXct(as.Date("2021-07-06"))), y=log10(1405.5625+1), color="#E69F00", shape=17,size=6)+
  geom_point(aes(x = as.POSIXct(as.Date("2021-08-09"))), y=log10(534.06+1), color="#CC79A7", shape=17,size=6)+
  geom_point(aes(x = as.POSIXct(as.Date("2021-07-06"))), y=log10(440.1357143+1), color="#D55E00", shape=17,size=6)+
  geom_point(aes(x = as.POSIXct(as.Date("2021-07-07"))), y=log10(116.8166667+1), color="#0072B2", shape=17,size=6)+
  geom_point(aes(x = as.POSIXct(as.Date("2021-07-12"))), y=log10(82.56+1), color="yellow3", shape=17,size=6)+
  scale_colour_manual(values = cols3)+
  scale_linetype_manual(values=LT)+
  theme_bw() +
  theme(panel.border = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"))+
  ggtitle("O. pajunii") +
  theme(plot.title = element_text(face = "bold.italic",size = 22)) +
  theme(axis.text=element_text(size=20, face = "bold"), 
        axis.title=element_text(size=24,face="bold")) +
  theme(legend.title = element_text(face = "bold",size = 20),
        legend.text=element_text(size=18,face="bold"),
        legend.position = "bottom") +  
  labs(x = (""), y="Log(Mean Spore Concentration+1)", color="Lake", linetype="Outbreak Size")+
  guides(linetype=guide_legend(nrow=3,byrow=TRUE))+  
  guides(color=guide_legend(nrow=3,byrow=TRUE))+
  theme(legend.key.width = unit(2, "cm"))

smooth.MicG
```

```{r,message=F,warning=F}
# Combining the four plots
combined = ggarrange(smooth.brood,smooth.MicG,smooth.past,smooth.metsch,
                     nrow = 2, ncol = 2,
                     common.legend = TRUE,
                     legend = "bottom")

combined = annotate_figure(combined,
                           left = text_grob("       Obligate Killers                   Continuous Shedders", 
                                            color = "#0072B2", face = "bold", size = 40,rot=90),
                           top = text_grob("", color = "black", face = "bold", size = 30))+
  annotation_custom(
    grid.polygon(x=c(0,1),
                 y=c(0.52,0.52),
                 gp = gpar(lwd = 5)))

combined

#### saving combined plot
ggsave(here("figures", "Combined_Plot_Mean_Spore_Concentration_And_Outbreak_Occurrence.jpg"), combined, units = "in", width = 20, height = 16, dpi = 300)
```

